plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\jdsie\\Desktop\\My-AI-Workspace\\rmc-website"
publishOrigin = "default"
base = "C:\\Users\\jdsie\\Desktop\\My-AI-Workspace\\rmc-website"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]